# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-16 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecontent',
            name='ordering',
        ),
        migrations.RemoveField(
            model_name='imagecontent',
            name='region',
        ),
        migrations.RemoveField(
            model_name='richtextcontent',
            name='ordering',
        ),
        migrations.RemoveField(
            model_name='richtextcontent',
            name='region',
        ),
    ]
