# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-16 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_auto_20171216_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcontent',
            name='urls_conf',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
