# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-02 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('pub_date', models.DateTimeField(verbose_name='publication date')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('categories', models.ManyToManyField(blank=True, related_name='blogentries', to='blog.Category', verbose_name='categories')),
                ('related_entries', models.ManyToManyField(blank=True, related_name='_article_related_entries_+', to='blog.Article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleImageContent',
            fields=[
                ('imagecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contents.ImageContent')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_articleimagecontent_set', to='blog.Article')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
                'ordering': ['ordering'],
            },
            bases=('contents.imagecontent',),
        ),
        migrations.CreateModel(
            name='ArticleRichTextContent',
            fields=[
                ('richtextcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contents.RichTextContent')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_articlerichtextcontent_set', to='blog.Article')),
            ],
            options={
                'verbose_name': 'rich text',
                'verbose_name_plural': 'rich texts',
                'ordering': ['ordering'],
            },
            bases=('contents.richtextcontent',),
        ),
        migrations.RemoveField(
            model_name='blogentry',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='blogentry',
            name='related_entries',
        ),
        migrations.RemoveField(
            model_name='blogentryimagecontent',
            name='imagecontent_ptr',
        ),
        migrations.RemoveField(
            model_name='blogentryimagecontent',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='blogentryrichtextcontent',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='blogentryrichtextcontent',
            name='richtextcontent_ptr',
        ),
        migrations.AlterField(
            model_name='comment',
            name='notify_new_comment',
            field=models.BooleanField(default=False, help_text='notify me for new comments', verbose_name='notify  new comments'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='notify_new_entry',
            field=models.BooleanField(default=False, help_text='notify me for new entries', verbose_name='notify new blog entries'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article'),
        ),
        migrations.DeleteModel(
            name='BlogEntry',
        ),
        migrations.DeleteModel(
            name='BlogEntryImageContent',
        ),
        migrations.DeleteModel(
            name='BlogEntryRichTextContent',
        ),
    ]
