"""
Django settings for krautswelt project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&&031vbll89z03)+lj8s*%9ea)7-5&lh2hlx#zmfrk7#effp*r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# needed for debug_toolbar
INTERNAL_IPS = ('127.0.0.1',)


#ALLOWED_HOSTS = ['192.168.178.80', ]
ALLOWED_HOSTS = ['local.krautswelt',]

MEDIA_ROOT = '%s/media' % BASE_DIR
MEDIA_URL = '/media/'
# Application definition


INSTALLED_APPS = [
    # 'contrib.admin.apps.AdminConfig',
    'app_settings.apps.AppSettingsConfig',
    'advanced_admin.apps.AdvancedAdminConfig',
    'core.contents.apps.ContentsConfig',
    'core.pages.apps.PagesConfig',
    'contrib.user.apps.UserConfig',
    'contrib.blog.apps.BlogConfig',
    'contrib.kcaptcha.apps.KcaptchaConfig',
    'django.contrib.admin',
    'mptt',
    'captcha',
    'versatileimagefield',
    'ckeditor',
    'content_editor',
    'rest_framework',
    'corsheaders',
    'webpack_loader',
    # 'debug_toolbar.apps.DebugToolbarConfig',
    #'krautswelt',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
DEBUG_TOOLBAR_PANELS = [
    'debug_toolbar.panels.versions.VersionsPanel',
    'debug_toolbar.panels.timer.TimerPanel',
    'debug_toolbar.panels.settings.SettingsPanel',
    'debug_toolbar.panels.headers.HeadersPanel',
    'debug_toolbar.panels.request.RequestPanel',
    'debug_toolbar.panels.sql.SQLPanel',
    'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    'debug_toolbar.panels.templates.TemplatesPanel',
    'debug_toolbar.panels.cache.CachePanel',
    'debug_toolbar.panels.signals.SignalsPanel',
    'debug_toolbar.panels.logging.LoggingPanel',
    'debug_toolbar.panels.redirects.RedirectsPanel',
]
MIDDLEWARE = [
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'krautswelt.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.pages.context_processors.navigation',
            ],
        },
    },
]

WSGI_APPLICATION = 'krautswelt.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

AUTH_USER_MODEL='user.User'

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '%s/../static/' % BASE_DIR
STATICFILES_DIRS = [ '%s/static/' % BASE_DIR, ]

#CAPTCHA_IMAGE_SIZE = (200, 100) 
CAPTCHA_FONT_SIZE = 28
CAPTCHA_FLITE_PATH = '/usr/bin/flite'

#CKEDITOR insert page links
CKEDITOR_CONFIGS = {
    "richtext-content": {
        # 'skin': 'office2013',
        'width': 900,
        'toolbar_Basic': [
            {'name':'styles',
                'items':['Styles', 'Format', 'Scayt']},
            {'name':'basicstyles',
                 'items':['Bold', 'Italic', 'Underline', 'Strike', 'RemoveFormat']},
            {'name':'clipboard',
                 'items':['Copy', 'Paste', 'Undo', 'Redo']},
            {'name':'links',
                 'items':['Link', 'Unlink', 'PageLink', 'Anchor']},
            {'name':'insert',
                 'items':['SpecialChar', 'HorizontalRule']},
            {'name':'paragraph',
                 'items':['NumberedList', 'BulletedList',]},
            {'name':'misc',
                 'items':['Source', 'Maximize','About' ]},
        ],
        'toolbar': 'Basic',
        'customConfig': "/static/krautswelt/js/ckeditor/config.js",
        # for extraPlugins see the customConfig File
    }
}

REST_FRAMEWORK = {
    # USe Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for anauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
    ]
}

CORS_ORIGIN_WHITELIST = (
    'localhost:8888',
    'localhost:8000',
    'local.krautswelt:8000',
    '127.0.0.1:3000'
    'localhost:3000'
)
CORS_ORIGIN_ALLOW_ALL = True
