# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 12:34
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='richtextcontent',
            options={'verbose_name': 'rich text', 'verbose_name_plural': 'rich texts'},
        ),
        migrations.AlterField(
            model_name='richtextcontent',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='text'),
        ),
    ]
