# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170315_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecontent',
            name='css_float',
            field=models.CharField(choices=[('l', 'left'), ('r', 'right'), ('n', 'none')], default='r', max_length=1, verbose_name='css float'),
        ),
    ]
