# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170316_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogentry',
            name='last_change',
        ),
    ]
