# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 19:20
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blogentry_last_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(verbose_name='text')),
            ],
            options={
                'verbose_name_plural': 'rich texts',
                'verbose_name': 'rich text',
                'abstract': False,
            },
        ),
    ]
