# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_entrycomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrycomment',
            options={},
        ),
        migrations.RemoveField(
            model_name='entrycomment',
            name='text',
        ),
        migrations.AddField(
            model_name='entrycomment',
            name='comment',
            field=models.TextField(default='leer', verbose_name='comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrycomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrycomment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='entrycomment',
            name='name',
            field=models.CharField(default='leer', max_length=100, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrycomment',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.BlogEntry'),
            preserve_default=False,
        ),
    ]
