# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170318_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('comment', models.TextField(verbose_name='comment')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('is_active', models.BooleanField(default=False, verbose_name='id active')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogEntry')),
            ],
        ),
        migrations.RemoveField(
            model_name='comments',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
