# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170319_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='website',
            field=models.URLField(blank=True, verbose_name='website'),
        ),
    ]
