# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-11 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20170319_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(help_text='Your email will never shown to anyone else', max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(help_text='Your name will be published.', max_length=100, verbose_name='name'),
        ),
    ]
