# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailsetting',
            unique_together=set([('app_label', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='floatsetting',
            unique_together=set([('app_label', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='integersetting',
            unique_together=set([('app_label', 'name')]),
        ),
    ]
