# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 14:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0002_auto_20171210_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooleanSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('value', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DateSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('value', models.DateField(default=datetime.datetime(2017, 12, 10, 14, 4, 20, 651670, tzinfo=utc))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DateTimeSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('value', models.DateTimeField(default=datetime.datetime(2017, 12, 10, 14, 4, 20, 653156, tzinfo=utc))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StringSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='stringsetting',
            unique_together=set([('app_label', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='datetimesetting',
            unique_together=set([('app_label', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='datesetting',
            unique_together=set([('app_label', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='booleansetting',
            unique_together=set([('app_label', 'name')]),
        ),
    ]
