# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0003_auto_20171210_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datesetting',
            name='value',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='datetimesetting',
            name='value',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
