# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-13 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0004_auto_20171210_1405'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booleansetting',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='datesetting',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='datetimesetting',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='emailsetting',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='floatsetting',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='integersetting',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='stringsetting',
            unique_together=set([]),
        ),
    ]
