# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-19 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_pageapplicationcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(max_length=155, unique=True, verbose_name='slug'),
        ),
    ]
