# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-26 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_auto_20171216_2348'),
        ('pages', '0006_page_overwrite_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='RichText',
            fields=[
                ('richtextcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contents.RichTextContent')),
            ],
            bases=('contents.richtextcontent',),
        ),
        migrations.RemoveField(
            model_name='pagerichtextcontent',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='pagerichtextcontent',
            name='richtextcontent_ptr',
        ),
        migrations.CreateModel(
            name='PageRichText',
            fields=[
                ('richtext_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.RichText')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages_pagerichtext_set', to='pages.Page')),
            ],
            options={
                'verbose_name': 'rich text',
                'verbose_name_plural': 'rich texts',
                'ordering': ['ordering'],
            },
            bases=('pages.richtext',),
        ),
        migrations.DeleteModel(
            name='PageRichTextContent',
        ),
    ]
